baseurl = "https://example.com"
copyright = "© Joseph Presley"
enablerobotstxt = true
languagecode = "en-us"
paginate = 50
theme = "paige"
timezone = "America/Los_Angeles"
titlecasestyle = "Go"

[languages.en]
weight = 10

[[languages.en.menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[languages.en.menu.main]]
identifier = "tech"
name = "Tech"
url = "/tech/"
weight = 20

[[languages.en.menu.main]]
identifier = "Comedy"
name = "Comedy"
url = "/comedy/"
weight = 40

[[languages.en.menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 100

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noclasses = false

[markup.tableofcontents]
endlevel = 6
ordered = true
startlevel = 2

[outputs]
home = [ "html", "json", "rss" ]

[params.authors.joseph-presley]
name = "Joseph Presley"

[params.paige.git]
commit_url_prefix = "https://github.com/willfaught/paige/commit/"

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"
